### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by GunniBusch** [josStorer/chatGPT-search-engine-extension#16]
Hey, would it be possible to add support for safari iOS? It would be really helpful.

**Comment by josStorer** [comment]
Actually supporting safari iOS is not a difficult task, but unlike macos, it means I would have to upload it to the app store, which is a bit of a tricky choice for me, my intention is just to provide users another choice with a richer feature set, implementing some features that upstream didn't support or refused to support

In fact, the author of upstream have been looking at the extension for safari for a long time (https://github.com/wong2/chatgpt-google-extension/issues/110), and I have mentioned my solution there (https://github.com/wong2/chatgpt-google-extension/issues/110#issuecomment-1399831569), but it seems that he shelved the issue, and I don't quite understand the original author's attitude towards safari support

At the same time, I do not intend to form a substantial competition with the original repo, nor do I intend to use it for profit, which is why I have not been upload my extension to any app stores so far
