### ISSUE TITLE
Firefox android addon

### ISSUE THREAD

**Issue by ayoung10** [josStorer/chatGPT-search-engine-extension#17]
Would it be possible to create a firefox android addon?
Beta users can add any addon: https://www.androidpolice.com/firefox-beta-107-android-install-any-browser-add-on/

The chatGPT addon for firefox works this way on android when viewing google in desktop mode, but when switching back to mobile view it disappears.

**Comment by josStorer** [comment]
did you enable `Insert chatGPT at the top of search results`, check [Readme#install-to-android](https://github.com/josStorer/chatGPT-search-engine-extension#install-to-android)

**Comment by ayoung10** [comment]
I'm using Firefox for Android, which can't use the chrome extension.

**Comment by josStorer** [comment]
Currently, custom add-on collections seem to only support adding addons that have already been uploaded to the store, but these chatGPT addons are not optimized for mobile devices.

This repository I maintain is indeed optimized for mobile devices, and you just need to enable `Insert chatGPT at the top of search results`, but I'm sorry, I haven't uploaded this addon to any app store, and there are currently no plans to do so.

As a result, the only way to use this addon on android is to install Kiwi Browser (This is not an advertisement, I just found that this browser can directly load local addons at present)

**Comment by josStorer** [comment]
By the way, this repository is open source under MIT license (based on the MIT part of upstream), in fact you can upload it to the store by yourself.

**Comment by josStorer** [comment]
@ayoung10 Firefox version is now available at https://addons.mozilla.org/firefox/addon/chatgptbox/
Install to Android: https://github.com/josStorer/chatGPTBox/wiki/Install#install-to-android

Due to the upstream repo being acquired and closed source, and there has been a period of time where issues and PRs in the upstream have gone unhandled. I decided to publish this extension to the store and keep open-source
