### ISSUE TITLE
Chat box dropping below search results

### ISSUE THREAD

**Issue by acasto** [josStorer/chatGPT-search-engine-extension#23]
After the most recent update the chat box is dropping down below the search results on particular output or reliably when input is entered that exceeds the width of the box. Example in the video below:

https://user-images.githubusercontent.com/199140/222948886-dfe03c39-1b42-42d0-9e3d-07c6f12e90f8.mp4

**Comment by josStorer** [comment]
Fixed in [v1.26.1](https://github.com/josStorer/chatGPT-search-engine-extension/releases)

You could reproduce this issue in the old version by entering a long continuous string of text, such as `fdcsjkofsjogkerjgoekrjghmboktremhboktrhmoiknbmfdoisgjhbnheriokjngbegergher`, and you can try again in the new version, the issue will not occur.

Furthermore, I noticed from your video that the current question input box seems inconvenient for long questions. The updated question input box in the new version supports multiple lines display.

**Comment by acasto** [comment]
Awesome. That worked great! Thanks.
