### ISSUE TITLE
Make it easier to pull from repo

### ISSUE THREAD

**Issue by Rex501st** [josStorer/chatGPT-search-engine-extension#24]
I use GitViewer in macOS to pull repos, but when I pull from this repo, due to how the repo is configured, I can't just easily sideload the extension in chrome. 

With an extension like the [following](https://github.com/iamadamdev/bypass-paywalls-chrome), I can pull it and point chrome to the top level folder and it'll recognize it is an extension. 

I think this would be much easier than downloading each version via a .zip file.

(I do apologize if there is another way to update the extension, if there is do tell!) 😅

**Comment by josStorer** [comment]
Great idea! I'm sorry I hadn't considered this more convenient way of updating before.

Due to the upstream repo being acquired and closed source half a month ago, and there has been a period of time where issues and PRs in the upstream have gone unhandled. I plan to publish this extension to the store recently after further integration and adjustment. Then, you will be able to update automatically.

**Comment by josStorer** [comment]
Waiting for store review
new repo: https://github.com/josStorer/chatGPTBox
changelog: https://github.com/josStorer/chatGPT-search-engine-extension/releases/tag/v2.0.0

**Comment by josStorer** [comment]
@Rex501st Available at chrome web store: https://chrome.google.com/webstore/detail/chatgptbox/eobbhoofkanlmddnplfhnmkfbnlhpbbo

**Comment by SocietasEvanescentes** [comment]
Thank you, and keep up the good work!
