### ISSUE TITLE
Selection tool aggressiveness 

### ISSUE THREAD

**Issue by acasto** [josStorer/chatGPT-search-engine-extension#29]
I love the power of the selection tool but it activates quite quickly, often over top of the selection, and sticks around requiring an additional click to hide. It would be nice to have the selection tool functionality accessible from a click of the plugin icon but  since it's currently used for settings might there be a way to tame down the select pop-up a bit?

**Comment by josStorer** [comment]
Currently you can uncheck all items in the SelectionTools Setting in order to stop creating SelectionTools
And you can use right-click menu to perform operations after selecting
Like this:
![image](https://user-images.githubusercontent.com/13366013/225374283-6622b834-e674-41c4-a439-f7eef3fa855f.png)

**Comment by acasto** [comment]
Excellent, that's perfect!
